languageCode = "en"
languageName = "English"
weight = 1
title = "geraldo@fedora:~$ |"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = ""
  description = "Personal Website and CV"

[params.author]
  name = "Geraldo Homero"
  image = "geraldohomero.jpg"
  headline = "Researcher @ Unicamp  <br> Digital Humanities | Python | C# | JavaScript <br><br>  PhD Student in Political Science, Unicamp"
  bio = "**Researcher** | Digital History | Digital Humanities | Data Analysis | Python  <br> **Developer** | C# | .NET | JavaScript | React.js "
  links = [
    { linkedin = "https://www.linkedin.com/in/geraldohomero/" },
    { github = "https://github.com/geraldohomero" },
    { gitlab = "https://gitlab.com/geraldohomero" },
    { codeberg = "https://codeberg.org/ghcoutoneto" },
    { orcid = "https://orcid.org/0000-0001-6686-7182" },
    { researchgate = "https://www.researchgate.net/profile/Geraldo-Couto-Neto"},
    { bluesky = "https://bsky.app/profile/geraldohomero.bsky.social"},
    { mastodon = "https://mastodon.social/@geraldohomero"},
    { x-twitter = "https://twitter.com/geraldohomero"},
    { instagram = "https://www.instagram.com/geraldohomero/" }

  ]