languageCode = "pt-br"
languageName = "Português"
weight = 2
title = "Geraldo Homero >_"

[params]
  displayName = "PT-BR"
  isoCode = "pt-br"
  rtl = false
  dateFormat = "2 January 2006"
  #logo = "img/bash.png"
  #secondaryLogo = "img/bash.png"
  description = "Geraldo's personal website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Geraldo Homero"
  image = "img/geraldohomero.jpg"
  headline = "C# | .NET | JavaScript | React.js"
  bio = "Hi"
  links = [
    { linkedin = "https://linkedin.com/in/geraldohomero" },
    { github = "https://github.com/geraldohomero" },
    { gitlab = "https://gitlab.com/geraldohomero"},
    { mastodon = "https://mastodon.social/@geraldohomero"},
    { twitter = "https://twitter.com/geraldohomero" },
    { instagram = "https://instagram.com/geraldohomero" }
  ]


  