languageCode = "pt-br"
languageName = "Português"
weight = 2
title = "geraldo@pop-os:~$ |"

[params]
  displayName = "Português"
  isoCode = "pt-br"
  rtl = false
  dateFormat = "2 January 2006"
  logo = ""
  description = "Website pessoal & CV"

[params.author]
  name = "Geraldo Homero"
  image = "geraldohomero.jpg"
  headline = "Monitor Front-end @ PUC Minas  <br> Humanidades Digitais | Python | C# | JavaScript <br><br> Mestre em História, UFJF "
  bio = "**Pesquisador** | História Digital | Humanidades Digitais | Análise de Dados | Python  <br> **Desenvolvedor** | C# | .NET | JavaScript | React.js"
  links = [
    { linkedin = "https://www.linkedin.com/in/geraldohomero/" },
    { github = "https://github.com/geraldohomero" },
    { gitlab = "https://gitlab.com/geraldohomero" },
    { orcid = "https://orcid.org/0000-0001-6686-7182" },
    { researchgate = "https://www.researchgate.net/profile/Geraldo-Couto-Neto"},
    { bluesky = "https://bsky.app/profile/geraldohomero.bsky.social"},
    { x-twitter = "https://twitter.com/geraldohomero"},
    { instagram = "https://www.instagram.com/geraldohomero/" },
  ]