[[main]]
none = "none"

[[main]]
name = "Home"
pageRef = "/"
identifier = "BIEPhK0TJV"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
identifier = "uWJeay3VG8"
weight = 2

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "8NfIvq6D4C"
weight = 3

[[main]]
name = "Academic"
pageRef = "academic"
identifier = "uJjKb2rFuO"
weight = 4

#[[main]]
#name = "Posts"
#pageRef = "posts"
#identifier = "CsX5EYuCL2"
#weight = 5

[[main]]
pre = "linkedin"
url = "https://linkedin.com/in/geraldohomero"
identifier = "eeoCMXECZk"
weight = 7

[[main]]
pre = "github"
url = "https://github.com/geraldohomero"
identifier = "eeoCMXEfZk"
weight = 7

[[footer]]
none = "none"

[[footer]]
name = "tags"
pageRef = "tags"
identifier = "mYVU27jzZj"
weight = 9999
