[[main]]
name = "Home"
pageRef = "/"
identifier = "BIEPhK0TJV"
weight = 10

[[main]]
name = "Sobre"
pageRef = "/about"
identifier = "uWJeay3VG8"
weight = 20

[[main]]
name = "Pesquisa"
pageRef = "research"
identifier = "uJjKb2rFuO"
weight = 30

[[main]]
name = "Projetos"
weight = 40

[[main]]
name = "Projetos de Pesquisa"
parent = "Projetos"
pageRef = "research-projects"
weight = 41

[[main]]
name = "Projetos Pessoais"
parent = "Projetos"
pageRef = "personal projects"
weight = 42

[[main]]
name = "Projetos da Graduação"
parent = "Projetos"
pageRef = "undergraduate projects"
weight = 43

[[main]]
name = "Blog"
pageRef = "blog"
identifier = "CsX5EYuCL2"
weight = 50

[[main]]
pre = "linkedin"
url = "https://linkedin.com/in/geraldohomero"
identifier = "eeoCMXECZk"
weight = 70

[[main]]
pre = "github"
url = "https://github.com/geraldohomero"
identifier = "eeoCMXEfZk"
weight = 80

[[main]]
pre = "orcid"
url = "https://orcid.org/0000-0001-6686-7182"
identifier = "eeoCMXJfZk"


[[footer]]
none = "none"

[[footer]]
name = "posts"
pageRef = "posts"
identifier = "DkX5LToCR8"
weight = 2

[[footer]]
name = "tags"
pageRef = "tags"
identifier = "mYVU27jzZj"
weight = 1
