languageCode = "en"
languageName = "English"
weight = 1
title = "Geraldo Homero >_"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  #logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  description = "Geraldo's personal website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Geraldo Homero"
  image = "img/geraldohomero.jpg"
  headline = "Dev | JavaScript | React.js | .NET | C# | Tailwind CSS"
  bio = "Hi"
  links = [
    { linkedin = "https://linkedin.com/in/geraldohomero" },
    { twitter = "https://twitter.com/geraldohomero" },
    { mastodon = "https://mastodon.social/@geraldohomero" },
    { instagram = "https://instagram.com/geraldohomero" },
    { github = "https://github.com/geraldohomero" }
  ]


  