baseURL = "http://example.org/"
theme = "loveit"
title = "Geraldo Homero"
languageCode = "pt"
languageName = "Portuguese"

[author]
  name = "Geraldo Homero"
  email = "geraldohomero@pm.me"
  link = "https://github.com/geraldohomero"

# Social links
[params.social]
    [params.social.Github]
    weight = 0
    id = "geraldohomero"
    prefix = "https://github.com/"
    title = "Github"
    
    [params.social.Instagram]
    weight = 2
    id = "geraldohomero"
    prefix = "https://instagram.com/"
    title = "Instagram"

    [params.social.Twitter]
    weight = 3
    id = "geraldohomero"
    prefix = "https://twitter.com/"
    title = "Twitter"

    [params.social.Linkedin]
    weight = 4
    id = "geraldohomero"
    prefix = "https://linkedin.com/in/"
    title = "LinkedIn"

    [params.social.orcid]
    weight = 5
    id = "0000-0001-6686-7182"
    prefix = "https://orcid.org/"
    title = "ORCID"

    [params.social.Zotero]
    weight = 6
    id = "geraldohomero"
    prefix = "https://zotero.org/"
    title = "Zotero"

    

[menu]
 [[menu.main]]
    weight = 1
    identifier = "home"
    pre = ""
    post = ""
    name = "Home"
    url = ""
    title = "Home"
  [[menu.main]]
    weight = 2
    identifier = "sobre"
    pre = ""
    post = ""
    name = "Sobre"
    url = "/sobre/"
    title = "Sobre"
  [[menu.main]]
    weight = 4
    identifier = "producoes"
    pre = ""
    post = ""
    name = "Produções"
    url = "/producoes/"
    title = "producoes"
  [[menu.main]]
    weight = 3
    identifier = "projetos"
    pre = ""
    post = ""
    name = "Projetos"
    url = "/projetos/"
    title = "projetos"
[[menu.main]]
    weight = 5
    identifier = "outros"
    pre = ""
    post = ""
    name = "Outros"
    url = "/outros/"
    title = "Outros"
[[menu.main]]
    weight = 6
    identifier = "contato"
    pre = ""
    post = ""
    name = "Contato"
    url = "/contato/"
    title = "contato"

[params]
  defaultTheme = "dark"
  gitRepo = "https://github.com/geraldohomero"
  fingerprint = ""
  dateFormat = "2006-01-02"
  title = "Geraldo Homero"
  description = "Site pessoal Geraldo Homero"
  images = [""]

 [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "https://0.academia-photos.com/32223304/9633463/39049482/s200_geraldo_homero_do.couto_neto.jpg"
      title = "Geraldo Homero"
      subtitle = "Dev | HTML | CSS | JavaScript | React | C# | .NET <br>Análise e Desenv. de Sistemas (PUC-Minas) <br> Pesquisador em História Digital"
      typeit = false
      social = true
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = false
      paginate = 6
      defaultHiddenFromHomePage = false

  # Header config
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "Geraldo"
      pre = ""
      post = " >_"
      typeit = false

 # Footer config
  [params.footer]
    enable = true
    custom = 'Powered by Hugo | LoveIt'
    hugo = false
    copyright = false
    author = true
    since = 2022
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'







