baseURL = "http://example.org/"
theme = "loveit"
title = "Geraldo Homero"
languageCode = "pt-br"
languageName = "Portuguese"

[author]
  name = "Geraldo Homero"
  email = "geraldohomero@pm.me"
  link = "https://github.com/geraldohomero"

# Social links
[params.social]
    GitHub = "geraldohomero"
    Linkedin = "geraldohomero"
    Twitter = "geraldohomero"
    Instagram = "geraldohomero"
    Gitlab = "geraldohomero"
    Mastodon = "@geraldohomero"

[menu]
 [[menu.main]]
    weight = 1
    identifier = "home"
    pre = ""
    post = ""
    name = "Home"
    url = ""
    title = "Home"
  [[menu.main]]
    weight = 2
    identifier = "sobre"
    pre = ""
    post = ""
    name = "Sobre"
    url = "/sobre/"
    title = "Sobre"
  [[menu.main]]
    weight = 4
    identifier = "producoes"
    pre = ""
    post = ""
    name = "Produções"
    url = "/producoes/"
    title = "producoes"
  [[menu.main]]
    weight = 3
    identifier = "projetos"
    pre = ""
    post = ""
    name = "Projetos"
    url = "/projetos/"
    title = "projetos"
# [[menu.main]]
#     weight = 5
#     identifier = "outros"
#     pre = ""
#     post = ""
#     name = "Outros"
#     url = "/outros/"
#     title = "Outros"
[[menu.main]]
    weight = 6
    identifier = "contato"
    pre = ""
    post = ""
    name = "Contato"
    url = "/contato/"
    title = "contato"

[params]
  defaultTheme = 'dark'
  gitRepo = "https://github.com/geraldohomero"
  fingerprint = ""
  dateFormat = "2006-01-02"
  title = "Geraldo Homero"
  description = "Site pessoal Geraldo Homero"
  images = [""]

 [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "https://avatars.githubusercontent.com/u/70844369?v=4"
      title = "<br>Geraldo Homero"
      subtitle = 'HTML | CSS | JavaScript | React | .NET | C#'
      typeit = false
      social = true
      disclaimer = '<br><font size="2"><b> Análise e Desenv. de Sistemas (PUC-Minas) <br></font>'
    # Home page posts
    [params.home.posts]
      enable = false
      paginate = 6
      defaultHiddenFromHomePage = false

  # Header config
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "Geraldo"
      pre = ""
      post = " >_"
      typeit = false

 # Footer config
  [params.footer]
    enable = true
    custom = '&#x1F12F Powered by <a href="https://gohugo.io" target="_blank">Hugo</a> | <a href="https://hugoloveit.com/" target="_blank">LoveIt</a>'
    hugo = false
    copyright = false
    author = true
    since = 2022
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'







