baseURL = "http://geraldohomero.github.io"
theme = "loveit"
title = "Geraldo Homero"
defaultContentLanguage = "pt-br"
languageCode = "pt-br"
languageName = "Português"

[author]
  name = "Geraldo Homero"
  email = "geraldohomero@pm.me"
  link = "https://github.com/geraldohomero"

# Social links
[params.social]
    GitHub = "geraldohomero"
    Linkedin = "geraldohomero"
    Twitter = "geraldohomero"
    Instagram = "geraldohomero"
    Gitlab = "geraldohomero"
    Mastodon = "@geraldohomero"

[menu]
[languages.en]
    weight = 1
    title = "Geraldo Homero"
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false
 [[languages.en.menu.main]]
    weight = 1
    identifier = "home"
    pre = ""
    post = ""
    name = "Home"
    url = ""
    title = "Home"
  [[languages.en.menu.main]]
    weight = 2
    identifier = "About"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
  [[languages.en.menu.main]]
    weight = 4
    identifier = "academic"
    pre = ""
    post = ""
    name = "Academic"
    url = "/academic/"
    title = ""
  [[languages.en.menu.main]]
    weight = 3
    identifier = "projects"
    pre = ""
    post = ""
    name = "Projects"
    url = "/projects/"
    title = ""
# [[languages.en.menu.main]]
#     weight = 5
#     identifier = "outros"
#     pre = ""
#     post = ""
#     name = "Outros"
#     url = "/outros/"
#     title = ""
[[languages.en.menu.main]]
    weight = 6
    identifier = "contact"
    pre = ""
    post = ""
    name = "Contact me"
    url = "/contact/"
    title = ""

[languages.pt-br]
    weight = 2
    title = "Geraldo Homero"
    languageCode = "pt-br"
    languageName = "Português"
    hasCJKLanguage = false
    [[languages.pt-br.menu.main]]
      weight = 1
      identifier = "home"
      pre = ""
      post = ""
      name = "Home"
      url = ""
      title = ""
    [[languages.pt-br.menu.main]]
      weight = 2
      identifier = "about"
      pre = ""
      post = ""
      name = "Sobre"
      url = "/about/"
      title = ""
    [[languages.pt-br.menu.main]]
      weight = 3
      identifier = "projects"
      pre = ""
      post = ""
      name = "Projetos"
      url = "/projects/"
      title = ""
    [[languages.pt-br.menu.main]]
      weight = 4
      identifier = "academic"
      pre = ""
      post = ""
      name = "Produções"
      url = "/academic/"
      title = ""
    [[languages.pt-br.menu.main]]
      weight = 5
      identifier = "contact"
      pre = ""
      post = ""
      name = "Contato"
      url = "/contact/"
      title = ""

[params]
  defaultTheme = 'dark'
  gitRepo = "https://github.com/geraldohomero"
  fingerprint = ""
  dateFormat = "2006-01-02"
  title = "Geraldo Homero"
  description = "Site pessoal Geraldo Homero"
  images = [""]

 [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "https://avatars.githubusercontent.com/u/70844369?v=4"
      title = "<br>Geraldo Homero"
      subtitle = 'HTML | CSS | JavaScript | React | .NET | C#'
      typeit = false
      social = true
      #disclaimer = '<br><font size="2"><b> Análise e Desenv. de Sistemas (PUC-Minas) <br> Mestrado em História (UFJF) </font>'
    # Home page posts
    [params.home.posts]
      enable = false
      paginate = 6
      defaultHiddenFromHomePage = false

  # Header config
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "Geraldo"
      pre = ""
      post = " >_"
      typeit = false

 # Footer config
  [params.footer]
    enable = true
    custom = '&#x1F12F Powered by <a href="https://gohugo.io" target="_blank">Hugo</a> | <a href="https://hugoloveit.com/" target="_blank">LoveIt</a>'
    hugo = false
    copyright = false
    author = true
    since = 2022
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'







